"""Register httk-analyse's generated typed result records lazily (no record module is imported here)."""

from httk.core import register_entry_record

# One generated record per vendored property definition (httk.analyse.property_records), then one per
# fixed-base statistic (``<base>_<derivation>``), registered as ``analyse-<name>`` with the class name the
# generator derives from that name.
for _name in (
    "activation_energy",
    "adsorption_energy",
    "arrhenius_prefactor",
    "band_gap",
    "bulk_modulus",
    "bulk_modulus_hill",
    "bulk_modulus_pressure_derivative",
    "bulk_modulus_reuss",
    "bulk_modulus_voigt",
    "charge_transition_level",
    "charged_defect_formation_energy",
    "chemical_potential_region",
    "compliance_tensor",
    "convex_hull_phase_diagram",
    "diffusion_coefficient",
    "diffusion_prefactor",
    "diffusion_running_integral",
    "diffusion_tensor",
    "direct_band_gap",
    "distinct_van_hove_function",
    "elastic_tensor",
    "electronic_density_of_states",
    "energy_above_hull_per_atom",
    "energy_prediction_errors",
    "equilibrium_energy",
    "equilibrium_volume",
    "fermi_energy",
    "force_prediction_errors",
    "formation_energy_per_atom",
    "heat_capacity_constant_pressure",
    "heat_capacity_constant_volume",
    "helmholtz_free_energy",
    "high_frequency_relative_permittivity",
    "intermediate_scattering_function",
    "isothermal_compressibility",
    "mean_squared_displacement",
    "migration_barrier_forward",
    "migration_barrier_reverse",
    "mode_gruneisen_parameters",
    "nve_energy_drift",
    "quasiharmonic_thermodynamics",
    "radial_distribution_function",
    "reaction_energy",
    "relative_effective_mass",
    "segregation_energy",
    "self_intermediate_scattering_function",
    "self_van_hove_function",
    "shear_modulus_hill",
    "shear_modulus_reuss",
    "shear_modulus_voigt",
    "shear_viscosity",
    "shear_viscosity_running_integral",
    "spin_channel_electronic_density_of_states",
    "static_relative_permittivity",
    "steinhardt_bond_order",
    "stress_prediction_errors",
    "surface_energy",
    "thermal_conductivity",
    "thermal_conductivity_running_integral",
    "thermal_conductivity_tensor",
    "total_energy_per_atom",
    "total_magnetic_moment",
    "universal_anisotropy_index",
    "velocity_autocorrelation",
    "velocity_power_spectrum",
    "vibrational_entropy",
    "vibrational_heat_capacity",
    "vibrational_internal_energy",
    "vibrational_thermodynamics",
    "volumetric_thermal_expansion",
    "zero_point_energy",
    # Statistics: <base definition name>_<derivation term name>.
    "atomic_force_bias",
    "atomic_force_mae",
    "atomic_force_maximum_absolute_error",
    "atomic_force_rmse",
    "stress_tensor_bias",
    "stress_tensor_mae",
    "stress_tensor_maximum_absolute_error",
    "stress_tensor_rmse",
    "total_energy_rmse",
    "total_energy_per_atom_bias",
    "total_energy_per_atom_mae",
    "total_energy_per_atom_maximum_absolute_error",
    "total_energy_per_atom_rmse",
    "heat_capacity_constant_pressure_standard_error",
    "heat_capacity_constant_volume_standard_error",
    "isothermal_compressibility_standard_error",
    "volumetric_thermal_expansion_standard_error",
    "shear_viscosity_mean",
    "thermal_conductivity_mean",
    "thermal_conductivity_tensor_mean",
    "thermal_conductivity_tensor_standard_error",
):
    register_entry_record(
        name="analyse-" + _name.replace("_", "-"),
        record="httk.analyse.property_records:" + "".join(part.capitalize() for part in _name.split("_")) + "Record",
        family="records",
        definition_id="https://schemas.httk.org/defs/v0.1/entrytypes/records",
    )
